---
title: "ASCVD 환자에게 중간 강도 statin과 ezetimibe의 combination과 고강도 statin의 차이 "
author: "eunkang kang"
format: revealjs
editor: 
  markdown: 
    wrap: 72
---

## Glossary_1

- Atherosclerotic Cardiovascular Disease(ASCVD) : 동맥경화성 심혈관질환;
  동맥 내벽에 지질과 염증 세포가 침착되어 형성된 plaque으로 인해 혈관이
  좁아지거나 파열되어 발생하는 모든 심혈관 질환
- Ex) 심근경색, 협심증, 뇌졸중, 말초동맥질환, 대동맥류

## Glossary_2

- Low-Density Lipoprotein Cholesterol(LDL_C) : 저밀도 지단백 콜레스테롤;
  간에서 합성된 콜레스테롤을 혈류를 통해 몸의 말단으로 운반.

- Statin : 스타틴; 간에서 콜레스테롤 합성을 억제하여 혈액 내 콜레스테롤
  수치를 낮춘다.

- Ezemitibe : 에제티미브; 소장에서 콜레스테롤이 체네로 흡수되는 것을
  차단한다.

## Background

- ASCVD환자는 고강도 스타틴을 통한 LDL 콜레스트롤 수치를 낮추는 것이
  가이드 라인이다.

- 중간 강도 스타틴과 에제티미브의 조합으로도 LDL-C를 충분히 낮추는 것이
  가능하다면 스타인의 부작용과 불내증을 감소할 것으로 기대.

- 그러나 두 요법의 랜덤화된 실험이 존재하지 않음.

- 따라서 두 요법 간 효능과 안정성을 비교하는 RACING trial 을 진행했다.

## Method

## study design

- investigator-initiated, multicentre, randomised, open-label,
  noninferiority.
- 26개의 기관에서 진행.

## participants

- 고농도의 statin을 복용하여 LDL-C 농도를 70mg/dL이하로 낮춰야하는 ASCVD
  환자들

- 심근경색(MI), 급성 관상동맥 증후군, 관상동맥 재개통술(혈관재건술) 또는
  기타 동맥 재개통술 병력, 허혈성 뇌졸중, 또는 말초동맥질환(PAD)

## Randomisation

- 환자들은 각각 1대1로 혼합복용 또는 고강도 단독 복용으로 지정

- permuted-block randomisation(4 or 6): 순열 블록 무작위 배정; 환자 4명
  혹은 6명이 한 block이 되어 한 블럭 안에서 배정 순서를 섞어 치료군과
  대조군으로 나누었다.

- 결과적으로 대조군과 치료군의 비율이 1대1이 될 수있다.

- LDL-C 농도가 100mg/dL 이하인지 여부, baseline에 당뇨병을 가지고
  있었는지 여부로 stratified 한다.

- 이는 복용 방법과 결과에 영향을 주는 핵심 요인들 사이의 상관관계를
  없앤다.

## Procedures

-스타틴 10mg + 에제티미브 10mg (혼합 복용) vs 스타틴 20mg (단독 복용)

- 2달, 6달, 이후 1년 마다 follow-up

## Outcomes

- Primary endpoint : 심혈관 질환으로 인한 사망, 주요 심혈관계 events, or
  비치명적 뇌졸증

- Secondary endpoint : 1년, 2년, 3년간 LDL-C 농도가 70mg/dDl 보다 감소한
  환자 비율

## Statistical analysis

## Sample size

- 기존 실험(IMPROVE-IT)에서 결과를 바탕으로 본 실험에서 예상 primary
  endpoint rate을 각각 13%(혼합복용), 14%(단독복용)로 설정.

- 혼합 복용이 비열등하기 위한 조건으로 2% point margin 설정(임상적으로
  차이가 없다고 고려되는 수치)

- 5% one-sided alpha error/ 80% power

## Sample size

- 기대 확률 p_1= 14% , p_2 = 13%
- C = 0.02 - Z\_{0.05} \* sqrt{Var(D)}
- C = -0.01 + Z\_{0.20} \* sqrt{Var(D)}
- Var(D) = {p_1(1-p_1) + p_2(1-p_2)} / {n}
- n =(Z\_{0.05} + Z\_{0.20})\^2 \* \[p_1(1-p_1) + p_2(1-p_2)\] / (0.02 -
  (-0.01))\^2
- n= 1605
- 두 그룹이고 예상 이탈률을 15%로 잡았다.
- N = 1605\*2 / 0.85 = 3780

## Statistical Analysis

- 범주형 변수: N% : Chi-square method

- 연속형 변수: Mean(SD) or Median(IQR): t-test

- log rank test(두 그룹 간의 생존 차이가 존재하는가)
- $$\chi^2 = \frac{\left( \sum_{j} (O_{1j} - E_{1j}) \right)^2}{\sum_{j} V_j}$$

- Cox regression & hazard ratio(두 투약 방법의 차이 수치)

- 단측 검정의 95% CI 상한\< 2.0%p인 경우 비열등하다

- Secondary endpoint : log rank test ; 다중성에 대한 보정이 되어있지
  않다. type I error를 유의하여 해석 
  

## Statistical Analysis

-primary analysis -intention to treat(ITT); 모든 환자들이 랜덤으로
지정되고 중간에 이탈자 또한 실험 참여자로 유지-\> 실험의 무작위성을
유지할 수 있다.

-민감도 분석:Per-protocal 집단 배정된 치료를 받지 않았거나, 배정치료
중단 기간이 전체 추적기간의 5%를 초과한 환자를 제외 한 결과.

-safety assessment: 약물을 투여받은 이력이 전혀 없는 사람을 제외.

## Result

-2017.02.14~2018.12.18 3780명 모집 -1894명은 혼합 복용, 1886명은 단독
복용 -두 집단의 기저 특성은 통계적으로 다르지 않았다. -한국인, 평균나이
64세, 남성 75%, 40% 심근경색 과거력 등

## Primary endpoint

- 병용 요법과 단독 요법

- primary endpoint 환자수 172(9.1%) vs 186(9.9%) (-0.78%; 90% CI −2∙39
  to 0∙83)

- 심혈관계 사망 8(0.4%) vs 6(0.3%) (HR 1∙34; 95% CI 0∙46 to 3∙85;
  p=0∙59)

- 주요 심혈관계 사건 153(8.1%) vs 167(8.9%) (HR 0∙91;95% CI 0∙73 to
  1∙14; p=0∙41)

- sensitivity 분석 결과: 160(9.1%) vs 158(9.4%) (−0∙29%; 90% CI −1∙97 to
  1∙37)

## Secondary endpoint_효능

-두 군의 1, 2, 3년째 LDL-C 목표(\<70mg/dL) 도달율은 각각 73% vs 55%, 75%
vs 60%, 72% vs 58% (all p-value \< 0.0001) -
$\chi^2 = \sum \frac{(O-E)^2}{E}$ - 여기서 O는 실제 환자수 ,E는 두
투약법과 무관한 평균 성공률로 계산한 기대 환자수 - 이때 기대 성공 확률은
2140/3348 , 1년째 itt population; 1675(혼합) : 1673(단독) - 혼합
성공$\frac{(1217 - 1070.8)^2}{1070.8} \approx \mathbf{19.96}$ - 혼합
실패$\frac{(458 - 604.2)^2}{604.2} =  \approx \mathbf{35.38}$ - 단독
성공: $\frac{(923 - 1069.2)^2}{1069.2} =  \approx \mathbf{20.00}$ - 단독
실패: $\frac{(750 - 603.8)^2}{603.8} =  \approx \mathbf{35.41}$ -
$$\chi^2 = 19.96 + 35.38 + 20.00 + 35.41 \approx \mathbf{110.75}$$ - df
= (행-1) \* (열 -1)= 1 , 0.0001의 임계값은 15.13

## Secondary endpoint_안전

-두 군의 이탈률, 약물 투여량 감소 환자수는 각각 88명(4.8%) vs
150(8.2%)(all p-value \< 0.0001)

## Conclusion 

-RACING trial은 3년의 관찰 결과, ASCVD 환자를 대상으로 중간 강도
statin과 ezetimibe의 병용요법이 고강도 statin 단독요법에 비해 임상적으로
열등하지 않으며, LDL-C 목표치 달성 및 복약 유지 면에서는 더 우월할 수
있음을 보였다.

## Discussion

- 환자수를 충분히 늘린다면 우월성 검정을 수행할 수도 있다. 다만 비용이
  늘어난다.
- 중간 강도 statin을 수용 가능 최대치만큼 복용중인 환자에게 ezetimibe의
  추가가 권장된다.
- 초기 단계에서 환자에게 statin을 늘리기보다 ezetimibe와 병용 용법을
  권장할 수 있다. \## Limitation
- open-label -\> nocebo effect
- 기대보다 낮은 event의 발생으로 2.0%p의 CI를 더 너그럽게 만들었다.
- 